using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Asp_Mvc_2015_2016.Controllers;
using System.Web;
using System.Web.Mvc;
namespace Asp_Mvc_2015_2016.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    //VB: Merged ApplicationUser met Gebruiker. Inherts from IdentityUser!!!
    [Bind(Include = "Id,UserName,Voornaam,Achternaam,Email,PhoneNumber,Gsm")]
    public class Gebruiker : IdentityUser
    {
        //VB: Added Data Annotations.
        [Required]
        [Display(Name = "Firstname", ResourceType = typeof(Resources.CultureResource))]
        public string Voornaam { get; set; }
        
        [Required]
        [Display(Name = "Lastname", ResourceType = typeof(Resources.CultureResource))]
        public string Achternaam { get; set; }
                
        [Phone(ErrorMessage="Geef een geldig telefoonnummer op.")]
        [Display(Name = "Mobile", ResourceType = typeof(Resources.CultureResource))]
        public string Gsm { get; set; }

        //VB: Override methods so we can annotate them! 
        //The Getters and setters are autogenerated on override, nothing changed.
        [Phone(ErrorMessage = "Geef een geldig telefoonnummer op.")]
        [Display(Name = "Phone", ResourceType = typeof(Resources.CultureResource))]
        public override string PhoneNumber
        {
            get { return base.PhoneNumber; }
            set { base.PhoneNumber = value; }
        }

        [Required]
        [Display(Name = "Username", ResourceType = typeof(Resources.CultureResource))]
        public override string UserName
        {
            get { return base.UserName; }
            set { base.UserName = value; }
        }

        [Required]
        [EmailAddress]
        [Display(Name = "Email", ResourceType = typeof(Resources.CultureResource))]
        public override string Email
        {
            get { return base.Email; }
            set { base.Email = value; }
        }
        

        // gebruiker en departement is many to many relatie -> apart model voor link tussen gebruiker en departement? -> ja dus...
        //apart model voor klanten toegewezen aan departement(en)
        [InverseProperty("Gebruiker")]
        public virtual ICollection<DepartementGebruiker> Departementen { get; set; }
        //apart model voor klanten toegewezen aan gebruiker(s).
        [InverseProperty("Gebruiker")]
        public virtual ICollection<GebruikerKlant> Klanten { get; set; }
       
        [InverseProperty("CreatedBy")]
        public virtual ICollection<Departement> DepartementsCreated { get; set; }
        [InverseProperty("EditedBy")]
        public virtual ICollection<Departement> DepartementsUpdated { get; set; }

        [InverseProperty("CreatedBy")]
        public virtual ICollection<Factuur> FacturenCreated { get; set; }
        [InverseProperty("EditedBy")]
        public virtual ICollection<Factuur> FacturenUpdated { get; set; }

        [InverseProperty("CreatedBy")]
        public virtual ICollection<Klant> KlantenCreated { get; set; }
        [InverseProperty("EditedBy")]
        public virtual ICollection<Klant> KlantenUpdated { get; set; }

        [InverseProperty("CreatedBy")]
        public virtual ICollection<UurRegistratie> UurRegistratiesCreated { get; set; }
        [InverseProperty("EditedBy")]
        public virtual ICollection<UurRegistratie> UurRegistratiesUpdated { get; set; }

        [InverseProperty("CreatedBy")]
        public virtual ICollection<FactuurDetails> FactuurDetailsCreated { get; set; }
        [InverseProperty("EditedBy")]
        public virtual ICollection<FactuurDetails> FactuurDetailsUpdated { get; set; }


    }
}